# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_total_pokes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_pokes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
