# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170823_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poker_id', models.IntegerField()),
                ('total_pokes', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('poking', models.ManyToManyField(related_name='poker', to='login.User')),
            ],
        ),
    ]
