# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_poker'),
    ]

    operations = [
        migrations.AddField(
            model_name='poker',
            name='poker_alias',
            field=models.CharField(default='Temp Entry', max_length=255),
            preserve_default=False,
        ),
    ]
